In [1]:
import pandas as pd

# Load one IRS file explore
df = pd.read_excel('../data/raw/irs_soi_table32_2022.xls',
                   header=None,
                   skiprows=10)


print(df.shape)
df.head(20)

(16, 37)

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,"Under $5,000 (includes deficits)",109318.0,-9.402630e+06,1.471520e+05,69204.0,215733.0,3910.0,15118.0,49840.0,2940.0,...,3951.0,3015.0,37014.0,11772.0,0.0,0.0,0.0,4851.0,-9733604.0,133826.0
1,"$5,000 under $10,000",119109.0,8.781820e+05,4.142300e+04,73056.0,543562.0,9739.0,11202.0,78236.0,4507.0,...,0.0,0.0,0.0,0.0,15.0,260.0,184.0,0.0,0.0,0.0
2,"$10,000 under $15,000",1370355.0,1.911266e+07,1.881780e+05,1335569.0,18677243.0,127472.0,5161.0,76555.0,4616.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,216.0,3989.0,25999.0
3,"$15,000 under $20,000",4429445.0,7.738333e+07,1.736237e+06,4405914.0,76982363.0,1687547.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"$20,000 under $25,000",4393888.0,9.878724e+07,3.804019e+06,4350811.0,97789356.0,3706442.0,25160.0,590577.0,32982.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,"$25,000 under $30,000",4801988.0,1.322478e+08,6.376403e+06,1632194.0,44244262.0,1421779.0,3140287.0,87189619.0,4852489.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,"$30,000 under $40,000",10791934.0,3.778382e+08,2.132230e+07,2682159.0,94149128.0,2086703.0,4982895.0,166111247.0,10581450.0,...,0.0,10.0,328.0,137.0,0.0,0.0,0.0,0.0,0.0,0.0
7,"$40,000 under $50,000",10680343.0,4.795230e+08,3.030934e+07,3198837.0,144170175.0,4201495.0,840036.0,37865047.0,2294458.0,...,41747.0,52.0,4336.0,1462.0,0.0,0.0,0.0,0.0,0.0,0.0
8,"$50,000 under $75,000",21378339.0,1.321300e+09,1.001036e+08,4701173.0,286006818.0,8515095.0,4118591.0,259142250.0,15644479.0,...,0.0,0.0,0.0,0.0,13.0,827.0,682.0,32.0,2052.0,2706.0
9,"$75,000 under $100,000",14549648.0,1.262290e+09,1.130794e+08,2340977.0,202082212.0,5977516.0,1955172.0,168378115.0,10189019.0,...,0.0,0.0,0.0,0.0,345.0,30486.0,19668.0,34.0,3981.0,7476.0
10,"$100,000 under $200,000",25547389.0,3.524739e+09,3.977584e+08,1555339.0,184287034.0,6139329.0,2036330.0,245816810.0,15109469.0,...,177369.0,1362.0,247210.0,93669.0,0.0,0.0,0.0,0.0,0.0,0.0
11,"$200,000 or more",12468373.0,6.729313e+09,1.465056e+09,137738.0,95469488.0,2039416.0,67469.0,30145924.0,1830286.0,...,331248227.0,344174.0,975509707.0,325341043.0,2977.0,2079267.0,1281790.0,166.0,206323.0,324785.0
12,* Estimate should be used with caution due to ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,** Data combined to prevent disclosure of spec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NOTE: Detail may not add to totals because of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"SOURCE: IRS, Statistics of Income Division, Pu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# See all 16 rows to identify drop
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 20)
df

,0,1,2,3,4,...,32,33,34,35,36
0,"Under $5,000 (includes deficits)",109318.0,-9.402630e+06,1.471520e+05,69204.0,...,0.0,0.0,4851.0,-9733604.0,133826.0
1,"$5,000 under $10,000",119109.0,8.781820e+05,4.142300e+04,73056.0,...,260.0,184.0,0.0,0.0,0.0
2,"$10,000 under $15,000",1370355.0,1.911266e+07,1.881780e+05,1335569.0,...,0.0,0.0,216.0,3989.0,25999.0
3,"$15,000 under $20,000",4429445.0,7.738333e+07,1.736237e+06,4405914.0,...,0.0,0.0,0.0,0.0,0.0
4,"$20,000 under $25,000",4393888.0,9.878724e+07,3.804019e+06,4350811.0,...,0.0,0.0,0.0,0.0,0.0
5,"$25,000 under $30,000",4801988.0,1.322478e+08,6.376403e+06,1632194.0,...,0.0,0.0,0.0,0.0,0.0
6,"$30,000 under $40,000",10791934.0,3.778382e+08,2.132230e+07,2682159.0,...,0.0,0.0,0.0,0.0,0.0
7,"$40,000 under $50,000",10680343.0,4.795230e+08,3.030934e+07,3198837.0,...,0.0,0.0,0.0,0.0,0.0
8,"$50,000 under $75,000",21378339.0,1.321300e+09,1.001036e+08,4701173.0,...,827.0,682.0,32.0,2052.0,2706.0
9,"$75,000 under $100,000",14549648.0,1.262290e+09,1.130794e+08,2340977.0,...,30486.0,19668.0,34.0,3981.0,7476.0
10,"$100,000 under $200,000",25547389.0,3.524739e+09,3.977584e+08,1555339.0,...,0.0,0.0,0.0,0.0,0.0
11,"$200,000 or more",12468373.0,6.729313e+09,1.465056e+09,137738.0,...,2079267.0,1281790.0,166.0,206323.0,324785.0
12,* Estimate should be used with caution due to ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
13,** Data combined to prevent disclosure of spec...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
14,NOTE: Detail may not add to totals because of ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
15,"SOURCE: IRS, Statistics of Income Division, Pu...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN

In [3]:
# Drop total and footnote rows, keep only the bracket rows
df_clean = df.iloc[0:12]

# Verify 12 rows
print(df_clean.shape)
df_clean

(12, 37)

,0,1,2,3,4,...,32,33,34,35,36
0,"Under $5,000 (includes deficits)",109318.0,-9.402630e+06,1.471520e+05,69204.0,...,0.0,0.0,4851.0,-9733604.0,133826.0
1,"$5,000 under $10,000",119109.0,8.781820e+05,4.142300e+04,73056.0,...,260.0,184.0,0.0,0.0,0.0
2,"$10,000 under $15,000",1370355.0,1.911266e+07,1.881780e+05,1335569.0,...,0.0,0.0,216.0,3989.0,25999.0
3,"$15,000 under $20,000",4429445.0,7.738333e+07,1.736237e+06,4405914.0,...,0.0,0.0,0.0,0.0,0.0
4,"$20,000 under $25,000",4393888.0,9.878724e+07,3.804019e+06,4350811.0,...,0.0,0.0,0.0,0.0,0.0
5,"$25,000 under $30,000",4801988.0,1.322478e+08,6.376403e+06,1632194.0,...,0.0,0.0,0.0,0.0,0.0
6,"$30,000 under $40,000",10791934.0,3.778382e+08,2.132230e+07,2682159.0,...,0.0,0.0,0.0,0.0,0.0
7,"$40,000 under $50,000",10680343.0,4.795230e+08,3.030934e+07,3198837.0,...,0.0,0.0,0.0,0.0,0.0
8,"$50,000 under $75,000",21378339.0,1.321300e+09,1.001036e+08,4701173.0,...,827.0,682.0,32.0,2052.0,2706.0
9,"$75,000 under $100,000",14549648.0,1.262290e+09,1.130794e+08,2340977.0,...,30486.0,19668.0,34.0,3981.0,7476.0
10,"$100,000 under $200,000",25547389.0,3.524739e+09,3.977584e+08,1555339.0,...,0.0,0.0,0.0,0.0,0.0
11,"$200,000 or more",12468373.0,6.729313e+09,1.465056e+09,137738.0,...,2079267.0,1281790.0,166.0,206323.0,324785.0

In [4]:
# all column names/numbers
for i, col in enumerate(df_clean.columns):
    print(f"Column {i}: {col}")

Column 0: 0
Column 1: 1
Column 2: 2
Column 3: 3
Column 4: 4
Column 5: 5
Column 6: 6
Column 7: 7
Column 8: 8
Column 9: 9
Column 10: 10
Column 11: 11
Column 12: 12
Column 13: 13
Column 14: 14
Column 15: 15
Column 16: 16
Column 17: 17
Column 18: 18
Column 19: 19
Column 20: 20
Column 21: 21
Column 22: 22
Column 23: 23
Column 24: 24
Column 25: 25
Column 26: 26
Column 27: 27
Column 28: 28
Column 29: 29
Column 30: 30
Column 31: 31
Column 32: 32
Column 33: 33
Column 34: 34
Column 35: 35
Column 36: 36

In [6]:
# Look at specific columns with full numbers
pd.set_option('display.float_format', '{:.2f}'.format)
df_clean.iloc[:, 0:5]

,0,1,2,3,4
0,"Under $5,000 (includes deficits)",109318.00,-9402630.00,147152.00,69204.00
1,"$5,000 under $10,000",119109.00,878182.00,41423.00,73056.00
2,"$10,000 under $15,000",1370355.00,19112665.00,188178.00,1335569.00
3,"$15,000 under $20,000",4429445.00,77383332.00,1736237.00,4405914.00
4,"$20,000 under $25,000",4393888.00,98787235.00,3804019.00,4350811.00
5,"$25,000 under $30,000",4801988.00,132247818.00,6376403.00,1632194.00
6,"$30,000 under $40,000",10791934.00,377838200.00,21322304.00,2682159.00
7,"$40,000 under $50,000",10680343.00,479522952.00,30309343.00,3198837.00
8,"$50,000 under $75,000",21378339.00,1321300231.00,100103598.00,4701173.00
9,"$75,000 under $100,000",14549648.00,1262289876.00,113079420.00,2340977.00
10,"$100,000 under $200,000",25547389.00,3524738541.00,397758377.00,1555339.00
11,"$200,000 or more",12468373.00,6729313224.00,1465055618.00,137738.00

In [5]:
#  first 5 columns to identify
df_clean.iloc[:, 0:5]

,0,1,2,3,4
0,"Under $5,000 (includes deficits)",109318.0,-9.402630e+06,1.471520e+05,69204.0
1,"$5,000 under $10,000",119109.0,8.781820e+05,4.142300e+04,73056.0
2,"$10,000 under $15,000",1370355.0,1.911266e+07,1.881780e+05,1335569.0
3,"$15,000 under $20,000",4429445.0,7.738333e+07,1.736237e+06,4405914.0
4,"$20,000 under $25,000",4393888.0,9.878724e+07,3.804019e+06,4350811.0
5,"$25,000 under $30,000",4801988.0,1.322478e+08,6.376403e+06,1632194.0
6,"$30,000 under $40,000",10791934.0,3.778382e+08,2.132230e+07,2682159.0
7,"$40,000 under $50,000",10680343.0,4.795230e+08,3.030934e+07,3198837.0
8,"$50,000 under $75,000",21378339.0,1.321300e+09,1.001036e+08,4701173.0
9,"$75,000 under $100,000",14549648.0,1.262290e+09,1.130794e+08,2340977.0
10,"$100,000 under $200,000",25547389.0,3.524739e+09,3.977584e+08,1555339.0
11,"$200,000 or more",12468373.0,6.729313e+09,1.465056e+09,137738.0

In [7]:
# Extract the column
df_working = df_clean[[0, 1, 2, 3]].copy()

# proper names
df_working.columns = ['income_bracket', 'num_returns', 'agi', 'total_income_tax']

# Compute effective tax rate
df_working['effective_tax_rate'] = df_working['total_income_tax'] / df_working['agi']

# Add year
df_working['year'] = 2022

#  result
df_working

,income_bracket,num_returns,agi,total_income_tax,effective_tax_rate,year
0,"Under $5,000 (includes deficits)",109318.00,-9402630.00,147152.00,-0.02,2022
1,"$5,000 under $10,000",119109.00,878182.00,41423.00,0.05,2022
2,"$10,000 under $15,000",1370355.00,19112665.00,188178.00,0.01,2022
3,"$15,000 under $20,000",4429445.00,77383332.00,1736237.00,0.02,2022
4,"$20,000 under $25,000",4393888.00,98787235.00,3804019.00,0.04,2022
5,"$25,000 under $30,000",4801988.00,132247818.00,6376403.00,0.05,2022
6,"$30,000 under $40,000",10791934.00,377838200.00,21322304.00,0.06,2022
7,"$40,000 under $50,000",10680343.00,479522952.00,30309343.00,0.06,2022
8,"$50,000 under $75,000",21378339.00,1321300231.00,100103598.00,0.08,2022
9,"$75,000 under $100,000",14549648.00,1262289876.00,113079420.00,0.09,2022
10,"$100,000 under $200,000",25547389.00,3524738541.00,397758377.00,0.11,2022
11,"$200,000 or more",12468373.00,6729313224.00,1465055618.00,0.22,2022

In [10]:
def load_and_clean_irs(filepath, year):
    # Load the file skip the title rows
    df = pd.read_excel(filepath, header=None, skiprows=10)

    # Keep only the 12 bracket rows
    df = df.iloc[0:12]

    # Extract the columns
    df_clean = df[[0, 1, 2, 3]].copy()

    # Rename column
    df_clean.columns = ['income_bracket', 'num_returns', 'agi', 'total_income_tax']

    # Replace * and ** with NaN
    df_clean = df_clean.replace(['*', '**'], pd.NA)

    # Compute effective tax rate
    df_clean['effective_tax_rate'] = df_clean['total_income_tax'] / df_clean['agi']

    # Add year
    df_clean['year'] = year

    return df_clean

In [11]:
# test
df_2022 = load_and_clean_irs('../data/raw/irs_soi_table32_2022.xls', 2022)
df_2022

,income_bracket,num_returns,agi,total_income_tax,effective_tax_rate,year
0,"Under $5,000 (includes deficits)",109318.00,-9402630.00,147152.00,-0.02,2022
1,"$5,000 under $10,000",119109.00,878182.00,41423.00,0.05,2022
2,"$10,000 under $15,000",1370355.00,19112665.00,188178.00,0.01,2022
3,"$15,000 under $20,000",4429445.00,77383332.00,1736237.00,0.02,2022
4,"$20,000 under $25,000",4393888.00,98787235.00,3804019.00,0.04,2022
5,"$25,000 under $30,000",4801988.00,132247818.00,6376403.00,0.05,2022
6,"$30,000 under $40,000",10791934.00,377838200.00,21322304.00,0.06,2022
7,"$40,000 under $50,000",10680343.00,479522952.00,30309343.00,0.06,2022
8,"$50,000 under $75,000",21378339.00,1321300231.00,100103598.00,0.08,2022
9,"$75,000 under $100,000",14549648.00,1262289876.00,113079420.00,0.09,2022
10,"$100,000 under $200,000",25547389.00,3524738541.00,397758377.00,0.11,2022
11,"$200,000 or more",12468373.00,6729313224.00,1465055618.00,0.22,2022

In [12]:
# Load all 6 function
df_32_2021 = load_and_clean_irs('../data/raw/irs_soi_table32_2021.xls', 2021)
df_32_2022 = load_and_clean_irs('../data/raw/irs_soi_table32_2022.xls', 2022)
df_32_2023 = load_and_clean_irs('../data/raw/irs_soi_table32_2023.xls', 2023)

# Check they all loaded correctly
print("2021 shape:", df_32_2021.shape)
print("2022 shape:", df_32_2022.shape)
print("2023 shape:", df_32_2023.shape)

2021 shape: (12, 6)
2022 shape: (12, 6)
2023 shape: (12, 6)

In [13]:
import pandas as pd

#  all 3 years together
df_table32_all = pd.concat([df_32_2021, df_32_2022, df_32_2023], ignore_index=True)

# Verify (12 x 3 years)
print("Combined shape:", df_table32_all.shape)
df_table32_all

Combined shape: (36, 6)

,income_bracket,num_returns,agi,total_income_tax,effective_tax_rate,year
0,"Under $5,000 (includes deficits)",146961.00,-12384174.00,259960.00,-0.02,2021
1,"$5,000 under $10,000",184757.00,1358544.00,78223.00,0.06,2021
2,"$10,000 under $15,000",1055682.00,14362205.00,211113.00,0.01,2021
3,"$15,000 under $20,000",3224975.00,57643020.00,1247485.00,0.02,2021
4,"$20,000 under $25,000",4511653.00,101727915.00,4047630.00,0.04,2021
...,...,...,...,...,...,...
31,"$40,000 under $50,000",10574219.00,475698679.00,29591551.00,0.06,2023
32,"$50,000 under $75,000",21494289.00,1328067520.00,96759453.00,0.07,2023
33,"$75,000 under $100,000",15065384.00,1306200302.00,114197559.00,0.09,2023
34,"$100,000 under $200,000",27211633.00,3769472892.00,409532689.00,0.11,2023
35,"$200,000 or more",13506728.00,6875280567.00,1468012878.00,0.21,2023

In [14]:
# all 3 years of Table 3.3 (filing status)
df_33_2021 = load_and_clean_irs('../data/raw/irs_soi_table33_2021.xls', 2021)
df_33_2022 = load_and_clean_irs('../data/raw/irs_soi_table33_2022.xls', 2022)
df_33_2023 = load_and_clean_irs('../data/raw/irs_soi_table33_2023.xls', 2023)

# Check shapes
print("2021 shape:", df_33_2021.shape)
print("2022 shape:", df_33_2022.shape)
print("2023 shape:", df_33_2023.shape)

2021 shape: (12, 6)
2022 shape: (12, 6)
2023 shape: (12, 6)

In [15]:
#  3 years of Table 3.3
df_table33_all = pd.concat([df_33_2021, df_33_2022, df_33_2023], ignore_index=True)

# Verify 36 rows
print("Combined shape:", df_table33_all.shape)
df_table33_all

Combined shape: (36, 6)

,income_bracket,num_returns,agi,total_income_tax,effective_tax_rate,year
0,No adjusted gross income,4098522.00,12327.00,33270.00,2.70,2021
1,"$1 under $5,000",8487025.00,35316.00,1427.00,0.04,2021
2,"$5,000 under $10,000",8944908.00,42757.00,7155.00,0.17,2021
3,"$10,000 under $15,000",10056377.00,2219399.00,255766.00,0.12,2021
4,"$15,000 under $20,000",9786580.00,5039256.00,1843123.00,0.37,2021
...,...,...,...,...,...,...
31,"$30,000 under $40,000",15210266.00,7609121.00,7550836.00,0.99,2023
32,"$40,000 under $50,000",13519034.00,5403353.00,9093190.00,1.68,2023
33,"$50,000 under $75,000",24135884.00,9890777.00,20255104.00,2.05,2023
34,"$75,000 under $100,000",15775468.00,6713621.00,17487047.00,2.60,2023
35,"$100,000 under $200,000",27602755.00,14416050.00,43512480.00,3.02,2023

In [16]:
# Combine Table 3.2 and Table 3.3  master dataset
df_master = pd.concat([df_table32_all, df_table33_all], ignore_index=True)

# 72 rows (36 + 36)
print("Master dataset shape:", df_master.shape)

# Save
df_master.to_csv('../data/processed/irs_master_clean.csv', index=False)

print(" Master CSV saved to data/processed/irs_master_clean.csv")

Master dataset shape: (72, 6)
 Master CSV saved to data/processed/irs_master_clean.csv